name: Docker Build And Push To Docker Hub

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Shadowsocks Poseidon
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout
        
      - name: Extract tag name
        id: tag
        uses: actions/github-script@v3
        with:
          result-encoding: string
          script: |
            return context.payload.ref.replace(/\/refs\/tags\//, '');
            
      - name: Replace version
            sed -i "15s|VERSION|${{ steps.tag.outputs.result }}|g" Dockerfile
                    
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
